/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedGameRouteImport } from './routes/_authed/game'
import { ServerRoute as ApiCheckPlayerServerRouteImport } from './routes/api/check-player'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGameRoute = AuthedGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCheckPlayerServerRoute = ApiCheckPlayerServerRouteImport.update({
  id: '/api/check-player',
  path: '/api/check-player',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/game': typeof AuthedGameRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/game': typeof AuthedGameRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/game': typeof AuthedGameRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/game' | '/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/game' | '/leaderboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/game'
    | '/_authed/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}
export interface FileServerRoutesByFullPath {
  '/api/check-player': typeof ApiCheckPlayerServerRoute
}
export interface FileServerRoutesByTo {
  '/api/check-player': typeof ApiCheckPlayerServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/check-player': typeof ApiCheckPlayerServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/check-player'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/check-player'
  id: '__root__' | '/api/check-player'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiCheckPlayerServerRoute: typeof ApiCheckPlayerServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/game': {
      id: '/_authed/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthedGameRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/check-player': {
      id: '/api/check-player'
      path: '/api/check-player'
      fullPath: '/api/check-player'
      preLoaderRoute: typeof ApiCheckPlayerServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedGameRoute: typeof AuthedGameRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedGameRoute: AuthedGameRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiCheckPlayerServerRoute: ApiCheckPlayerServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
